### PR TITLE
Update for Android 13

### PR DESCRIPTION
**Pull request by byReqz**
Hi, I have updated the module for Android 13. This has been tested on Lineage 20 with MicroG v0.2.27.223616.

### CODE REVIEW

**Comment by urcle0815** [comment]
I will test it as soon as possible and leave you a feedback.

**Comment by sn-00-x** [comment]
Thank you so much! I don't have an A13 device and can't test, so I will merge as soon as @urcle0815 confirms that this works.

**Comment by alexanderrogling** [comment]
I will try this tomorrow as said in the mention "post" I will try it tomorrow morning and reply asap, and probably as soon as 6:30 my time :)

Thank for this fork in advance @byReqz

**Comment by wesleyote** [comment]
I flashed this successfully on my OnePlus 9P on Android 13 (crDroid, a LineageOS-based ROM). I have installed Magisk, Google TTS and the Google App per the README. I'm only able to test Android Auto on a wired connection.

All the Android Auto features work except for "GameSnacks". Opening any game results in an "Android Auto has encountered an unexpected error" message on the headunit. Pressing the Exit button just returns you to the apps page.

Assistant seems to work perfectly if installed in addition to the Google app. Maps, Youtube Music, Spotify, etc. can also be installed for navigation and music streaming services. They all seem functional thus far.

**Pull request merged**
